-- Usuni?cie tabeli PROFIT_BY_STATE
DROP TABLE PROFIT_BY_STATE CASCADE CONSTRAINTS;

-- Tworzenie tabeli PROFIT_BY_STATE
CREATE TABLE PROFIT_BY_STATE
(
    state VARCHAR2(2) PRIMARY KEY,
    profit NUMBER(8,2)
);

-- Usuni?cie tabeli ZIP
DROP TABLE ZIP;

-- Tworzenie tabeli ZIP
CREATE TABLE ZIP
(
    ID_ZIP NUMBER(5) PRIMARY KEY,
    ZIP VARCHAR2(5) UNIQUE,
    STATE VARCHAR(2)
);

-- Usuni?cie tabeli TIME
DROP TABLE TIME;

-- Tworzenie tabeli TIME
CREATE TABLE TIME
(
    ID_TIME NUMBER(3) PRIMARY KEY,
    MONTH NUMBER(2),
    YEAR NUMBER(4),
    CONSTRAINT UNIQUE_MONTH_YEAR UNIQUE(MONTH, YEAR)
);

-- Usuni?cie tabeli SALE
DROP TABLE SALE;

-- Tworzenie tabeli SALE
CREATE TABLE SALE
(
    id_sale NUMBER(8) PRIMARY KEY,
    ID_ZIP NUMBER(5) REFERENCES ZIP(ID_ZIP),
    ID_TIME NUMBER(3) REFERENCES TIME(ID_TIME),  -- Poprawka: odniesienie do tabeli TIME
    sales_amount NUMBER(8,2),
    CONSTRAINT UNIQUE_ZIP_TIME UNIQUE(ID_ZIP, ID_TIME) -- poprawka w nazwach kolumn
);

--JEST JAKO? TRIGGER? WYZWALACZ, BIFOR- IVAN (BEFORE)(OM-ON ,,IVAN,,)
DROP SEQUENCE SEQ_ZIP;
CREATE SEQUENCE SEQ_ZIP;
DROP SEQUENCE SEQ_TIME;
CREATE SEQUENCE SEQ_TIME;
DROP SEQUENCE SEQ_SALE;
CREATE SEQUENCE SEQ_SALE;


CREATE OR REPLACE TRIGGER TRIG_SET_ID_ZIP
BEFORE INSERT ON ZIP
FOR EACH ROW
BEGIN
    :NEW.ID_ZIP := SEQ_ZIP.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRIG_SET_ID_TIME
BEFORE INSERT ON TIME
FOR EACH ROW
BEGIN
    :NEW.ID_TIME := SEQ_TIME.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRIG_SET_ID_SALE
BEFORE INSERT ON SALE
FOR EACH ROW
BEGIN
    :NEW.ID_SALE := SEQ_SALE.NEXTVAL;
END;
/